### ISSUE TITLE
[JOSS Review] Comments and Suggestions

### ISSUE THREAD

**Issue by giswqs** [davemlz/eemont#22]
**Repo:**

- Suggest removing all .ipynb_checkpoints. You might want to add .ipynb_checkpoints to .gitignore so that these unnecessary folders won’t be pushed to GitHub. (see pull request https://github.com/davemlz/eemont/pull/21)
- Suggest adding the docs website (https://eemont.readthedocs.io) to the About section located at the upper-right corner of the repo page. 
- Adding a Table of Content for README.rst, making it easier to navigate this long document.
- In README.rst, the `Contribution Steps` section probably belongs to a subsection of `Contributing`.
- You might want to consider publishing the package on conda-forge. Unless your package is available on conda-forge, other conda packages can’t list eermont as a dependency. Check out my tutorial on publishing a conda package if needed. 
- The installation instructions can be improved by adding instructions such as how to update the package, install from GitHub, install from conda-forge (if it exists), etc. 
- For all notebooks, `!pip install earthengine-api` is not needed because eemont/geemap already has earthengine-api as a dependency. 
- Be cautious about using the GEE logo. Google is pretty picky about how their logos are used: https://www.google.com/permissions/logos-trademarks. I was warned before by a Google employee not to use the GEE logo. Unless you have received permission from Google to use/modify the GEE logo, you might want to design your own logo that is distinctive from the GEE logo.   

**Paper:** 

- The writing can be improved. I made some minor changes. See pull request https://github.com/davemlz/eemont/pull/21

**Comment by giswqs** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/3168

**Comment by davemlz** [comment]
Hi, @giswqs!

Thank you very much for the suggestions and the PR! I'll merge it and start working on your comments and suggestions. I've planned to publish the package on conda-forge, but I have to figure out how to use a dependency that is not there, after that I'll publish it there!

**Comment by giswqs** [comment]
It seems all dependencies listed in requirements.txt are available on conda-forge. Which specific dependency are you referring to that's not available on conda-forge?

**Comment by davemlz** [comment]
You're right! It was my bad, I thought `geopy` wasn't on conda-forge.

**Comment by davemlz** [comment]
Hi, @giswqs!

I have updated the README (and also the docs and tutorials) following your suggestions (https://github.com/davemlz/eemont/commit/447d8237ce144e769476b2dbf7c97cb7b8f8b549, https://github.com/davemlz/eemont/commit/4513fb714c86d090d2de8b4818d7306c3cec286f).

I have also submitted the package to conda-forge (All checks passed) and I'm waiting for the review!

Thank you very much for your suggestions, comments and contributions!

**Comment by davemlz** [comment]
Hi, @giswqs!

`eemont` is now on `conda-forge`! I have updated the README and the Docs with the installation guidelines.

**Comment by giswqs** [comment]
@davemlz Looks good. Congrats on publishing eemont on conda-forge!

**Comment by davemlz** [comment]
Thank you very much, @giswqs!
