### ISSUE TITLE
[JOSS Review] Comments

### ISSUE THREAD

**Issue by patrickcgray** [davemlz/eemont#28]
It is clear this is a substantial scholarly effort and represents an excellent contribution to the remote sensing/scientific computing community. I don't think the paper/repo needs any substantial changes. It installed easily in a fresh virtual envronment via `pip` and `conda` and documentation was relatively straightforward. All code examples worked for me, installation was as documented, and the QGIS functionality worked as documented. I think it will be easy for GEE practitioners to implement.

Comments:
- I do think the statement of need could be improved by stating the need first rather than stating what you've done first. I think this could be a single sentence or two clarifying that "The typical pre-processing and processing steps and long, and complex, making it challenging to move from data selection to analysis and these steps have been simplified with intelligent defaults and clearer more pythonic syntax." Just a template but I think that helps readers rapidly understand the main problem.
- The [tutorials](https://eemont.readthedocs.io/en/latest/tutorials.html) are excellent, ran correctly in colab, and I learned a few nice tricks from them. I would recommend linking them in a clear spot in the README document instead of just on the [docs](https://eemont.readthedocs.io/en/latest/tutorials.html).

**Comment by kbarnhart** [comment]
linking with joss review issue
openjournals/joss-reviews/issues/3168

**Comment by davemlz** [comment]
Hi, @patrickcgray! Thank you very much for the comments! I'll start working on your suggestions and let you know as soon as they're ready! :)

**Comment by davemlz** [comment]
Hi, @patrickcgray!

I have updated the paper following your suggested template for the Statement of Need and added some links to the README (and also to the main page of the Docs), including a link to the tutorials! :)

Thank you for the comments and suggestions again, @patrickcgray!

**Comment by patrickcgray** [comment]
Hey @davemlz nice work, I think everything looks good on my end! Closing this issue.

**Comment by davemlz** [comment]
Thank you, @patrickcgray!
