### ISSUE TITLE
EVI calculation is not correct - S2 values need adjustment

### ISSUE THREAD

**Issue by philippgaertner** [davemlz/eemont#29]
It seems that, in the section "Overloaded Operators", where you calculate the EVI with S2_SR you need to use reflectance values. Please multiply the pixel values by 'scale' (0.0001) when you use Sentinel-2 SR products.

**Comment by davemlz** [comment]
Thank you again, @philippgaertner! I'll modify the "Overloaded Operators" section in the README (and also the "Spectral Indices" section). This was my bad, again.

**Comment by davemlz** [comment]
Hi, @philippgaertner! I have updated the examples in the README (and in the Docs). I also updated the "Spectral Indices" section in case someone wants to use an index (using that example) that requires scaling. Thank you again!
