### ISSUE TITLE
ee.ImageCollection.getTimeSeriesByRegion breaks when specifying bands=None

### ISSUE THREAD

**Issue by sebimarkgraf** [davemlz/eemont#43]
**Describe the bug**
When choosing the bands as `None` as specified in the default and the documentation to get all images, the following error is thrown:
``` python
TypeError: object of type 'NoneType' has no len()
```

**To Reproduce**
Do not specify the bands parameter when using `´getTimeSeriesByRegion``.

**Setup (please complete the following information):**
 - OS:  Linux
 - python version: 3.8
 - eemont version: 0.2.5
 - earthengine-api version: 0.1.269

**Additional context**
Problem seems to be due to ``setNA`` using the bands parameter without checking for ``None``.
Potential fixes could be changing ``setNA`` or settings the bands parameter to all bands when checking for ``None``.

**Comment by davemlz** [comment]
Fixed! If you download the dev version, it should work! :)

**Comment by sebimarkgraf** [comment]
Oh wow, that was quick. Thank you very much!
