### ISSUE TITLE
[JOSS Review] Package test automation/instructions

### ISSUE THREAD

**Issue by elbeejay** [davemlz/eemont#5]
Looks like there is a set of [tests](https://github.com/davemlz/eemont/tree/master/tests) that have been written for this package. Can you either automate these via some sort of continuous integration, or provide detailed instructions in the documentation so that an individual can run the tests locally?

I would consider adding a "developer installation" set of instructions to the documentation so that an aspiring contributor could follow steps to clone, install, locally test and make eventually make contributions to the project, but I leave that decision up to you.

Thanks.

This comment relates to the ongoing [JOSS review](https://github.com/openjournals/joss-reviews/issues/3168) of this package, comment pertains to the "Documentation" section of the JOSS reviewer guidelines:

> Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by davemlz** [comment]
Hi, @elbeejay!

Perfect, I'll work on it and let you know when it is finished! (I'll do the same for #4)

Thank you!

**Comment by davemlz** [comment]
Hi, @elbeejay!

I have added, for now, a general section for Contribution Guidelines that covers #4 and #5. You can find them in the [README](https://github.com/davemlz/eemont/blob/master/README.rst) and in the [CONTRIBUTING](https://github.com/davemlz/eemont/blob/master/CONTRIBUTING.rst) files. I plan to extend them in the future with more details on how to contribute for specific features of the package.

Thank you!

**Comment by elbeejay** [comment]
Awesome, thanks!
