### ISSUE TITLE
Update `tasseledCap` docstrings

### ISSUE THREAD

**Issue by aazuspan** [davemlz/eemont#63]
Once I finish adding the new coeffs for L8 and L9 in `ee_extra` (r-earthengine/ee_extra#42) I can update the docstrings for `ee.Image.tasseledCap` and `ee.ImageCollection.tasseledCap`here to include the new reference and platform list :)

**Comment by davemlz** [comment]
Perfect! Thanks, @aazuspan! :rocket:
