### ISSUE TITLE
COPERNICUS/S2_HARMONIZED

### ISSUE THREAD

**Issue by Ivo-G** [davemlz/eemont#68]
eemont is not working on the dataset COPERNICUS/S2_HARMONIZED

**Comment by Ivo-G** [comment]
Dataset is Working but not loading indexes. THNKS

**Comment by davemlz** [comment]
Hi!

This is being addressed in [ee-extra](https://github.com/r-earthengine/ee_extra) and soon it will be available in `eemont`!

Best,

David

**Comment by davemlz** [comment]
The dataset was succesfully added and it will be available in the upcoming release of eemont!

Thank you!
