### ISSUE TITLE
What visParams should i use for al lthe indices available in spectral indices?

### ISSUE THREAD

**Issue by kaushikCanada** [davemlz/eemont#70]
There are lots of indices in https://github.com/awesome-spectral-indices/awesome-spectral-indices.
When i try to view them it requires visParams parameter and the colour palette. Can you put a guide or soemthing to give the proper visparams for viewing on map?
For example to view [BLFEI](https://doi.org/10.1080/10106049.2018.1497094): Built-Up Land Features Extraction Index. what should be my visParams?

**Comment by davemlz** [comment]
Hi @kaushikCanada!

That depends entirely on the index. For any index it is recommended to look into the reference paper and check how it works. In the case of the BLFEI, the formula is a normalized difference, so the valid range is [-1,1]. Now, the values inside this range may vary according to the land cover you're in. But, as mentioned before, it is recommended to look into the index's paper.

Jus as general vis options, you can use `{min:-1,max:1}` or `{min:0,max:1}` for normalized differences (palette is black and white by default in GEE, this depends more on your taste, just make sure that you use divergent or sequetial palettes accordingly). Usually, most indices have values greater than 0 for the target (e.g. NDVI). NDVI goes from -1 to 1 but vegetation is always positive. I have never tried BLFEI, but it would probably follow the same principle here.

Cheers!

David
