### ISSUE TITLE
MODIS/061/MOD09A1

### ISSUE THREAD

**Issue by masands** [davemlz/eemont#73]
Hi

This product is now available in https://storage.googleapis.com/earthengine-stac/catalog/MODIS/catalog.json

Thanks

**Comment by davemlz** [comment]
Hi!

This is being addressed in [ee-extra](https://github.com/r-earthengine/ee_extra) and soon it will be available in `eemont`!

Best,

David

**Comment by davemlz** [comment]
The dataset was succesfully added and it will be available in the upcoming release of eemont!

Thank you!
