### ISSUE TITLE
tasseled cap transformation for COPERNICUS/S2_SR

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [davemlz/eemont#74]
Hi,
I am wondering if it is possible to add the tasseled cap transformation for COPERNICUS/S2_SR
Thanks,
Daniel

Exception: Sorry, satellite platform not supported for tasseled cap transformation! Use one of ['COPERNICUS/S2', 'MODIS/006/MCD43A4', 'LANDSAT/LC09/C02/T1_L2', 'LANDSAT/LC09/C02/T1_TOA', 'LANDSAT/LC08/C02/T1_L2', 'LANDSAT/LC08/C02/T2_L2', 'LANDSAT/LC08/C01/T1_TOA', 'LANDSAT/LC08/C01/T1_RT_TOA', 'LANDSAT/LC08/C01/T2_TOA', 'LANDSAT/LE07/C01/T1_TOA', 'LANDSAT/LE07/C01/T1_RT_TOA', 'LANDSAT/LE07/C01/T2_TOA', 'LANDSAT/LT05/C01/T1', 'LANDSAT/LT05/C01/T2', 'LANDSAT/LT04/C02/T1_L2', 'LANDSAT/LT04/C02/T2_L2', 'LANDSAT/LT04/C01/T1', 'LANDSAT/LT04/C01/T2']

**Comment by davemlz** [comment]
Hi, @Daniel-Trung-Nguyen!

We need specific TC transformation coefficients for each platform according to the processing level. At the moment all the available platforms have a published paper with the coefficients (including S2 L1C, but not S2 L2A). When we find one, or if you find one, please let us know so we can include it! :)

CC: @aazuspan

Best regards,

David
