### ISSUE TITLE
Pixel calculation after cloud masking

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [davemlz/eemont#75]
Hi,
It does seem to me that the masked pixel values were set to 0 instead of null and thus they were also used in statistical calculations (e.g. mean/median)
Photos below show that the NDVI value of the masked areas seem to be lower than the surrounding area.

Cloud free image (2022-04-02)
![image](https://user-images.githubusercontent.com/22897462/183250676-563a9a3a-de3f-44a2-9716-b8181ea15e1d.png)

Subsequent cloud-masked image (2022-04-04)
![image](https://user-images.githubusercontent.com/22897462/183250532-d1a30cd1-babe-4d43-a68e-55f692a66a05.png)

First image NDVI
![image](https://user-images.githubusercontent.com/22897462/183250754-de17c4f0-8db4-493f-b4ad-175a02d617ce.png)

NDVI of the median from the 2 images.
![image](https://user-images.githubusercontent.com/22897462/183250799-25211ea7-cb9b-4ddd-a32b-f194fb97b4d8.png)

**Comment by Daniel-Trung-Nguyen** [comment]
When I ran the same location on code.earthengine.google.com using the code boilerplate from https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2_SR, the cloud was not masked at all. Is this a bug or am I missing something?
Thanks,
Daniel

```
/**
 * Function to mask clouds using the Sentinel-2 QA band
 * @param {ee.Image} image Sentinel-2 image
 * @return {ee.Image} cloud masked Sentinel-2 image
 */
function maskS2clouds(image) {
  var qa = image.select('QA60');

  // Bits 10 and 11 are clouds and cirrus, respectively.
  var cloudBitMask = 1 << 10;
  var cirrusBitMask = 1 << 11;

  // Both flags should be set to zero, indicating clear conditions.
  var mask = qa.bitwiseAnd(cloudBitMask).eq(0)
      .and(qa.bitwiseAnd(cirrusBitMask).eq(0));

  return image.updateMask(mask).divide(10000);
}

var point = ee.Geometry.Point([150.5773, -28.1182])
var dataset = ee.ImageCollection('COPERNICUS/S2_SR')
                  .filterDate('2022-04-01', '2022-04-06')
                  .filterBounds(point)
                  // Pre-filter to get less cloudy granules.
                  .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE',50))
                  .map(maskS2clouds);

var visualization = {
  min: 0.0,
  max: 0.3,
  bands: ['B4', 'B3', 'B2'],
};

Map.setCenter(150.5773, -28.1182,15);

Map.addLayer(dataset.mean(), visualization, 'RGB');

```
![image](https://user-images.githubusercontent.com/22897462/183251688-2a130a7e-40a7-4b5e-9c3e-87134c207d8c.png)

**Comment by Daniel-Trung-Nguyen** [comment]
Apparently I added unmask() after clipping the imagecollection to an ROI that was why the mask was replaced by zero.

**Comment by davemlz** [comment]
Don't worry! :)
