### ISSUE TITLE
Support for computing indices for Sentinel-1

### ISSUE THREAD

**Issue by Geethen** [davemlz/eemont#76]
**Is this a Feature Request for eemont or for eeExtra?**
eemont

**Is your feature request related to a problem? Please describe.**
I have been trying to compute spectral indices listed in espectro for S1 but have had no success- I am getting the impression that it is not yet supported?

I keep getting an error stating the platform is not supported.

**Describe the solution you'd like**
I preprocess Sentinel-1 data using [this package](https://github.com/adugnag/gee_s1_ard) and then need to compute radar indices.

**Comment by davemlz** [comment]
Oh God you're right! I forgot to add S1. I'll work on it and I'll let you know when it is ready! :)

Thank you!

**Comment by davemlz** [comment]
https://github.com/r-earthengine/ee_extra/issues/45

**Comment by davemlz** [comment]
Done!

It will be available for the next version of `eemont` :rocket:!
