### ISSUE TITLE
How does the spectralIndices function pick correct bands for an index?

### ISSUE THREAD

**Issue by holgervirro** [davemlz/eemont#85]
I was looking at the documentation for the eemont package at [https://eemont.readthedocs.io/en/latest/](https://eemont.readthedocs.io/en/latest/) and saw an example of calculating spectral indices for a Sentinel-2 image collection with the following method:

`S2 = (ee.ImageCollection('COPERNICUS/S2_SR').filterBounds(point).closest('2020-10-15').maskClouds(prob = 70).scaleAndOffset().spectralIndices(['NDVI','NDWI','BAIS2']))`

I had a question about the `spectralIndices` function applied in this example.

How does the function know which bands to use for calculating the indices? Does it somehow detect the data source (e.g. Sentinel-2) and then pick the suitable bands needed for a particular index?

Looking forward to your response!

**Comment by davemlz** [comment]
You are right!

We pre-select the bands from some popular platforms beforehand ;)

The bands are selected according to the Awesome Spectral Indices standard: https://github.com/awesome-spectral-indices/awesome-spectral-indices?tab=readme-ov-file#expressions

I hope this solves your question!

Cheers,

David

**Comment by holgervirro** [comment]
Thanks for the confirmation!
